### PR TITLE
start building in module mode

### LINKED ISSUE #61: use of internal package not allowed
$ go get -u github.com/ejcx/passgo
src/github.com/ejcx/passgo/vendor/golang.org/x/crypto/nacl/secretbox/secretbox.go:38:2: use of internal package not allowed

### PR DESCRIPTION
**Pull request by dmitshur**
Start building passgo in module mode, which is available in Go 1.11
and newer.

Add go.mod and go.sum files. Since there's already a v2.0.0 tag, start
at v2 instead of v1. This is primarily a command, not a library, so
it's viable not to immediately increase major version by one despite
the pre-go.mod v2.0.0 tag. However, a new v2.1.0 release tag will need
to be created after this change is merged, so that the latest version
includes this change.

Given we're now building in module mode, start using [`debug.ReadBuildInfo`](https://godoc.org/runtime/debug#ReadBuildInfo)
to determine the version, instead of hardcoding it into the source code.

Remove vendor directory for now; it's no longer necessary and can be
re-added if/when there's a concrete need for it.

Fixes #61

/cc @FiloSottile FYI.

### CODE REVIEW

**Comment by ejcx** [comment]
Ill give these a test in the next couple days, and if I merge I will cut a new release and update docs if they need to be updated.

Thanks a lot for making this change.

**Comment by dmitshur** [comment]
Friendly ping. 🙂

**Comment by dmitshur** [comment]
Friendly ping. Please let me know if I can help in making this PR easier to review.

**Comment by ejcx** [comment]
Sorry Dmitri, I've been busy. Ill try to take a look this week.

**Comment by ejcx** [comment]
Just gave it a try. I had taken a look a few months ago but honestly didn't have a recent enough version of go to test go modules, then I got distracted. All looks good now. Thanks for the PR and I apologize for the delay!

**Comment by dmitshur** [comment]
No worries and thank you!

**Comment by dmitshur** [comment]
@ejcx As a heads up, you'll need to make a newer `v2.x.y` tag that includes this change, otherwise the current [installation command in the README](https://github.com/ejcx/passgo#installation) will not pick it up.

**Comment by ejcx** [comment]
Done!

**Pull request merged**
