### PR TITLE
Fixes password generation algorithm to ensure the password length is as specified

### PR DESCRIPTION
**Pull request by hsson**
After using the password generation function for a while I noticed that sometimes the length would be totally off from what I had specified as an argument. I managed to track the problem and found that using `string(letter)` sometimes created a string consisting of multiple characters, not just 1. I figure this is because of UTF-8, but I'm not sure.

This simple fix makes sure the generated password is always of the length specified.

### CODE REVIEW

**Comment by ejcx** [comment]
Are you sure this is the right fix?

The key reason why generate sometimes returns a wildly different number of characters (especially at smaller numbers) is because of the specification requirement.

Even if we hit the right number of characters, we don't return a password until the complexity requirement is met. Knowing that makes me skeptical of this change.
https://github.com/ejcx/passgo/blob/master/pc/pc.go#L206

**Comment by hsson** [comment]
I see. Well I'm thinking of the use case where a website has a restriction for the maximum password length. Maybe it could work if it starts over or something if the specs are met but the length isn't exactly correct? It would be much better for the user if the generate function gave the correct password length from the beginning, otherwise the user probably needs to run the function again.

**Comment by ejcx** [comment]
I agree. Generate doesn't work exactly how it should. I think it should be a little smarter but I'm not sure exactly what to do yet.

**Comment by hsson** [comment]
This probably isn't the prettiest nor the smartest solution to the problem - but it ensures correctness.

**Comment by ejcx** [comment]
I think I'd rather just punt on this for now, until I figure out exactly how this should be handled. I would like to be able to configure the password specs but I'm not sure how to work this in all together.

**Comment by hsson** [comment]
Sounds resonable! This soultion really only works with the case where all specs are needed anyway. Perhaps flags could be used to specify which specs to use? And it defaults to all of them? Like ```passgo generate -uld``` or something similar would generate a password with the Upper, Lower, and Digit specs. Just a suggestion :smile: I'll leave this for now.

**Comment by ejcx** [comment]
I merged a fix for this some time ago.

**Pull request closed without merging**
