### PR TITLE
Added installation and first time setup instructions to README.md

### PR DESCRIPTION
**Pull request by nicr9**
For people who are unfamiliar with golang and how to install packages I've left links to pages that explain getting that setup. Also explicit instructions on how to initialise the vault and create a master password.

### CODE REVIEW

**Comment by ejcx** [comment]
Thanks. There may need to be a mention of running `go build` and copying the binary to your $PATH

**Comment by nicr9** [comment]
Hey, thanks for the feedback!

I think `go get ...` builds the executable as well. 

What do you think if I added a bit that explains how to add `$GOPATH` to `$PATH`?

**Comment by ejcx** [comment]
That would be wonderful. Thanks a lot.

**Comment by nicr9** [comment]
Updated with comment on adding `$GOPATH` to `$PATH`.

**Comment by ejcx** [comment]
Thanks. I appreciate the pull.

**Pull request merged**
