### PR TITLE
Add copy to clipboard option. Minor refactoring.

### PR DESCRIPTION
**Pull request by ejcx**
Use flag args. Using os.Args will become increasingly
complex as more and more command line flags get added.

### CODE REVIEW

**Comment by ejcx** [comment]
@hsson I changed quite a few things from your PR #4. Would like to have you review. The things I changed from yours.

1. No copy package. That seemed like overkill to me
2. Vendor the clipboard package.
3. Minor structure changes to the weird getArguments package. 
4. Moved to using flag functions to access args instead of os.Arg, because it will be hard not to in the future.

I really appreciate the work you did to get me started. You did the hard part I just did a little bit of cleaning.

**Comment by hsson** [comment]
I like most of the changes you made, @ejcx. Really good to get rid of the Copy package - I guess I first thought that it would be it's own command, but that doesn't make sense since it was implemented as a flag anyway. 

And it makes a lot of sense to use the flag package for the argument handling. The way you split the arguments into a sub-arguments makes it less complex indeed. 

However, I think the new ```getSubArguments``` function seems a bit strange. For starters, if a command needs one argument, but none are specified an empty string is returned (this is how you wanted it). But if a command needs two or more arguments and not enough are specified then the log message "Not enough args" will be shown. I find this a bit strange. 

I think the dilemma is that if no arguments are specified you need to return an empty string for commands that doesn't require any arguments to work. But for commands that do require arguments to work there needs to be some sort of mechanism to check for this and give an error if not enough arguments are specified. This is the reason for having the ```required bool``` in my previous ```getArguments``` function. 

Also, there seems to be off-by-one errors in the code above. For example ```passgo genereate 15``` gave me an "Not enough args" log message. You have the line ```pwlenStr := getSubArguments(subArgs, 1)```, which should use the index 0 instead of 1 now that you are inputting the list of sub-arguments instead of all agruments. And none of the commands where you used ```getSubArguments(subArgs, ALLARGS)``` actually supports more than one argument (from what I can tell), so it doesn't really make sense to use it as input - those should also be ```getSubArguments(subArgs, 0)```.

I fixed the problems mentioned, but I'm not sure what the best way would be to push it up. Should I open a new pull request and reference this one?

**Comment by ejcx** [comment]
Nice catch on generate. I passed the wrong number in. I passed 1 instead of 0 to getSubArguments.

I don't think this is such a bad thing, having an empty string returned from getSubArguments. That's how the flag package works.
https://golang.org/pkg/flag/#Arg

The subcommands or the callers of getSubArguments might just need to handle an empty string.

Does this address all the issues you can think of ?

**Comment by hsson** [comment]
Generate wasn't the only one not working correctly - take a look at the latest commit in PL #4 which addresses all the issues mentioned.

**Comment by ejcx** [comment]
Got a chance to fix this. The biggest problem was off by one errors. I vendored the clipboard package, cleaned up the flag parsing and argument parsing, and I think we are in much better shape now.

Thanks for the review and the PR @hsson you were unbelievable helpful.

**Comment by ejcx** [comment]
Good call. Thanks @hsson

**Pull request merged**
