### PR TITLE
Implements feature requested in #1 to allow copying of password directly to clipboard

### PR DESCRIPTION
**Pull request by hsson**
This pull request implements the feature to directly copy the password for a site to the clipboard. The feature uses https://github.com/atotto/clipboard for the actual clipboard handling.

Unfortunately some code from the Show package could not be reused for actually getting the password.

### CODE REVIEW

**Comment by hsson** [comment]
To use the feature, use "passgo --copy <site name>", the shorthand paramter "-c" can also be used.

**Comment by ejcx** [comment]
Thanks for the pull. 

I think the proper way to handle the `--copy` and `-c` flags is by use of a flagSet.

I also think it's probably better to create a `getArguments` function instead of an `enoughArguments` function. getArguments would do all of the string joining and bound checking in one place. It could even just return an empty string on failure.

**Comment by hsson** [comment]
Alright, I'll make it use the ```flags``` package instead!

Wouldn't it require more code in the long run if every command needs to check if it gets an empty string as input? And this would probably be needed since it doesn't seem very user friendly to not print anything if not enough arguments are passed. I guess the alternative would be to print in the ```getArguments``` function if not enough arguments are passed, but still return an empty string. What are your opinions? I can implement the ```getArguments``` as you specified if you want to :smile:

**Comment by ejcx** [comment]
I like getArguments. To save code you could probably even Fatalf for things that require an argument and are not provided one inside of getArguments.

Thanks a lot @hsson!

**Comment by hsson** [comment]
These latest two commits should fix what we discussed. I hope the flag implementation is like you meant. I haven't used the ```flag``` package before :smile:

**Comment by ejcx** [comment]
Oh great work! I think getArguments turned out a lot cleaner. I'll do some testing and try to merge this shortly

**Comment by hsson** [comment]
Thanks! I totally agree! Much cleaner now. Looking forward to seeing it merged!

**Comment by hsson** [comment]
@ejcx This could probably be closed now since #14 is merged :smile: I'm glad I could help!!

**Comment by ejcx** [comment]
Good call thanks @hsson

**Pull request closed without merging**
